### ISSUE TITLE
Error 60000 or 52200

### ISSUE THREAD

**Issue by KostaSaizo7** [kuroppoi/entralinked#1]
Hi there!
I am using melonDS 0.9.5 with Pokemon White 2. In the Nintendo WFC Settings I have set both DNSs as my local ip.
I have entralinked.jar running.
When I am using the Game Sync from the Cgear, after saving the game, I get an error 60000 the first time or 52200 if I try again.
I am not sure if I am doing everything right.

![image](https://github.com/kuroppoi/entralinked/assets/39852873/4fd68efe-290a-426f-8e9e-776d74a25ac7)

**Comment by kuroppoi** [comment]
Erasing any existing Wi-Fi Connection settings and trying again should solve the issue!

**Comment by KostaSaizo7** [comment]
Do you mean in the Nintendo WFC Settings? I deleted all 3 connections, then created a new one but still error 60000.
Btw I can connect to riiconnect24 (167.86.108.126) and kaeru (178.62.43.212) successfully.
![image](https://github.com/kuroppoi/entralinked/assets/39852873/f7cf9ee4-ca73-457c-a787-1adb01fb685b)

**Comment by kuroppoi** [comment]
> Do you mean in the Nintendo WFC Settings? I deleted all 3 connections, then created a new one but still error 60000. Btw I can connect to riiconnect24 (167.86.108.126) and kaeru (178.62.43.212) successfully. ![image](https://user-images.githubusercontent.com/39852873/248575225-f7cf9ee4-ca73-457c-a787-1adb01fb685b.png)

Yes, in those settings, go one level higher (back button) and go press the orange "Options" button. Then use the "Erase Nintendo WFC Configuration" option.

Unfortunately, you will have to do this again when you want to switch back to KaeruWFC.
This is because the game keeps track of your profile ID, and throws error `60000` when the server sends the incorrect one.
It shouldn't really be a problem unless you have important ranking data that you do not wish to lose, so it might not be a bad idea for me to look into setting up a proxy system.

**Comment by KostaSaizo7** [comment]
It works! Awesome!
Maybe you can write about erasing settings in README
![image](https://github.com/kuroppoi/entralinked/assets/39852873/b96288f9-513e-42de-a1c9-21479ccb454f)

**Comment by kuroppoi** [comment]
Glad it all worked out! I'll add a section about erasing settings to the README file.
