### ISSUE TITLE
Unable to see primary DNS [linux]

### ISSUE THREAD

**Issue by jackj1** [kuroppoi/entralinked#15]
![image](https://github.com/kuroppoi/entralinked/assets/62434031/472f8023-f04b-42f9-8fb8-c8c2703eefea)
As you can see above, the content does not resize with the window so I am unable to see what primary DNS to use on my DS. Not sure if this problem is caused by java on linux or my window manager, either way, would it be possible for you to include the DNS in the text output to the terminal? That way we could see the DNS even if there is a problem with how the GUI displays.

Also, the "open user dashboard" button doesn't open anything.

**Comment by kuroppoi** [comment]
Currently, the DNS is only logged if you run Entralinked with the `disablegui` flag like so: `java -jar entralinked.jar disablegui`
I will change this later so that it is logged regardless of that.
If the dashboard button doesn't work for whatever reason then you can manually navigate to http://127.0.0.1/dashboard.profile.html

**Comment by jackj1** [comment]
Thanks, I'm now able to see the DNS, however when I use it I get error 52100, which isn't listed in the troubleshooting section. I don't think my connection is the issue as I'm able to access DS wifi with the poke classic servers DNS if I use that one instead.

**Comment by kuroppoi** [comment]
This just happens sometimes, I’m not entirely sure why.
Could be related to messing with Nintendo WFC settings, but who knows.
Unfortunately, you will have to wait 24 hours before you can do anything.
