### ISSUE TITLE
Error code: 52210

### ISSUE THREAD

**Issue by Bumbus506** [kuroppoi/entralinked#32]
Tried setting the primary dns in my 3ds to the one that was given to me by entralinked. Got this error code when attempting to connect to the internet in game. 

There are no other connections set up on my 3ds and I even tried deleting the one I had and making a new one from scratch. Both my 3ds and laptop are using the same internet connection. I haven't touched any other settings aside from setting "auto obtain dns" to no. 

I've never gotten this issue when using the poke classic network or even just connecting to the internet with an automatically obtained dns. I know it probably doesn't matter but I tried running a connection test with the dns I got from entralinked and it failed.

**Comment by kuroppoi** [comment]
It's not exactly the same error code but try this: https://github.com/kuroppoi/entralinked/wiki/Troubleshooting#052110-x

**Comment by kuroppoi** [comment]
Seeing "This Wi-Fi Connection ID does not exist" in the PID tool simply means that the user doesn't exist on the server, which makes sense since it hasn't created a user yet due to not being able to connect properly.

Feel free to post your debug log, just make sure to do it right after a failed attempt to ensure it contains the relevant info.

**Comment by kuroppoi** [comment]
Good to hear, glad the issue has been resolved!
