### ISSUE TITLE
Error 52100 Unable to connect to Wi-Fi

### ISSUE THREAD

**Issue by yagirliris** [kuroppoi/entralinked#50]
after attempting all of the listed troubleshooting, and following the quick start instructions, i continue to get error code 52100 before reaching the point of tucking in a pokemon. I am a novice when it comes to computers, and am not sure what to try from here

**Comment by sinfuego12** [comment]
I have the same issue

**Comment by ShinHaguchi56** [comment]
I also have a similiar issue and I've tried everything I can and nothigs working, feels very odd when I've seen others use it

**Comment by kuroppoi** [comment]
52100 occurs when the game can't connect to the DNS server.

It's kinda difficult to pinpoint the cause of issues like this, and if none of the solutions listed in the troubleshooting guide worked then I'm not entirely sure what else the problem could be.

I don't recommend doing this but if you're feeling brave then you _could_ completely turn off Windows Defender for a bit and try to connect while it's off. If it still doesn't work then it's most likely not that.

Some similar cases have occurred in the past (#32 and #33) where it turned out to be a separate antivirus causing issues, so that might be worth looking into as well.

**Comment by yagirliris** [comment]
Okay. So I've done a lot of messing around with settings and I've looked back at the similar cases.
I've shut off antivirus firewalls and Windows Defender, and tried every other troubleshooting method (i'm pretty sure)
The last thing I could think to do was check the active ports on my computer through a command prompt.
Upon doing so, I found that ports 80, 443, and 29900 are all listed as listening.
However, port 53, which entralinked says the DNS server is supposedly listening through, is not listed anywhere I can see.

Is this a possible issue with my computer, or do you have any other ideas as to what could be preventing me from making that connection to the DNS server? Apologies if this is possibly a basic question, i really don't know computers >.<

**Comment by kuroppoi** [comment]
It should be listed if you run `netstat -aof -p udp | findstr :53` in a command prompt.

If you're absolutely certain that it's not a firewall or antivirus problem then maybe the DNS itself is incorrect.
Make sure that the DNS it tells you to use [matches your PC's IPv4 address.](https://support.microsoft.com/en-us/windows/find-your-ip-address-in-windows-f21a9bbc-c582-55cd-35e0-73431160a1b9)

**Comment by yagirliris** [comment]
I've been trying this all connected to a public network on my router. As a last-ditch attempt, before i saw your response, i reconfigured my dsi's internet settings, and switched over to the non-5G private network on my home's router. Reconfiguring to the set DNS and performing a connection test succeeded, and upon attempting to connect to game sync, i finally got error code 60000!

So somehow the switch from public network to private network fixed it and im really not sure how?

Following the troubleshooting guide and updating the PID allowed me to pass that error and generate a Game Sync ID.

Incidentally, upon checking the PC's IPv4 address, it did match what entralinked was telling me. also listed there was a separate "IPv4 DNS servers" address? I don't know if that has anything to do with it.

**Comment by ShinHaguchi56** [comment]
oddly enough i'm still unable to but i'll see what I can do to fix it for me, my ipv4 matches and everything but its not working out for me but i'll keep trying

**Comment by ShinHaguchi56** [comment]
update 2: tried turning off or disabling things in the firewall, that did nothing, i can't connect to my router so that's just not an option and my phone's hotspot works but that ultimately does nothing. I have to just understand this program doesn't work at all since it doesn't seem to do anything idk if my debug log will help but here: 
[debug.log](https://github.com/kuroppoi/entralinked/files/15151222/debug.log)

**Comment by kuroppoi** [comment]
Yeah it looks like it's unable to connect to the DNS server.
If none of the listed solutions worked for you then I'm not entirely sure either, sorry.
